# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/annotation.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/annotation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/annotation.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x02\n\x0e\x43\x61seAnnotation\x12\x15\n\rannotation_id\x18\x01 \x01(\x03\x12\x12\n\npayment_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61uthor_user_id\x18\x03 \x01(\t\x12?\n\x0f\x61nnotation_type\x18\x04 \x01(\x0e\x32&.ces.payment_resolution.AnnotationType\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x16\n\x0e\x63ontact_method\x18\x06 \x01(\t\x12\x17\n\x0f\x63ontact_outcome\x18\x07 \x01(\t\x12\x17\n\x0f\x63ontacted_party\x18\x08 \x01(\t\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xc1\x01\n\x0e\x41nnotationType\x12\x1f\n\x1b\x41NNOTATION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x41NNOTATION_TYPE_CASE_NOTE\x10\x01\x12#\n\x1f\x41NNOTATION_TYPE_OVERRIDE_REASON\x10\x02\x12\"\n\x1e\x41NNOTATION_TYPE_CONTACT_RECORD\x10\x03\x12&\n\"ANNOTATION_TYPE_INVESTIGATION_NOTE\x10\x04\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.annotation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_ANNOTATIONTYPE']._serialized_start=374
  _globals['_ANNOTATIONTYPE']._serialized_end=567
  _globals['_CASEANNOTATION']._serialized_start=84
  _globals['_CASEANNOTATION']._serialized_end=371
# @@protoc_insertion_point(module_scope)
