# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/config_change.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/config_change.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/config_change.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x03\n\x1a\x43onfigurationChangeRequest\x12\x11\n\tchange_id\x18\x01 \x01(\x03\x12\x16\n\x0eparameter_name\x18\x02 \x01(\t\x12\x15\n\rcurrent_value\x18\x03 \x01(\t\x12\x16\n\x0eproposed_value\x18\x04 \x01(\t\x12\x11\n\trationale\x18\x05 \x01(\t\x12\x18\n\x10projected_impact\x18\x06 \x01(\t\x12\x13\n\x0bproposed_by\x18\x07 \x01(\t\x12\x13\n\x0b\x61pproved_by\x18\x08 \x01(\t\x12\x16\n\x0ereview_comment\x18\t \x01(\t\x12:\n\x06status\x18\n \x01(\x0e\x32*.ces.payment_resolution.ConfigChangeStatus\x12/\n\x0bproposed_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0breviewed_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x64\x65ployed_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa1\x02\n\x1d\x43onfigurationThresholdVersion\x12\x12\n\nversion_id\x18\x01 \x01(\x03\x12\x16\n\x0eparameter_name\x18\x02 \x01(\t\x12\x17\n\x0fparameter_value\x18\x03 \x01(\t\x12\x12\n\nchanged_by\x18\x04 \x01(\t\x12\x13\n\x0b\x61pproved_by\x18\x05 \x01(\t\x12\x11\n\trationale\x18\x06 \x01(\t\x12\x19\n\x11\x63hange_request_id\x18\x07 \x01(\x03\x12\x32\n\x0e\x65\x66\x66\x65\x63tive_from\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x65\x66\x66\x65\x63tive_to\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xeb\x01\n\x12\x43onfigChangeStatus\x12$\n CONFIG_CHANGE_STATUS_UNSPECIFIED\x10\x00\x12 \n\x1c\x43ONFIG_CHANGE_STATUS_PENDING\x10\x01\x12!\n\x1d\x43ONFIG_CHANGE_STATUS_APPROVED\x10\x02\x12!\n\x1d\x43ONFIG_CHANGE_STATUS_REJECTED\x10\x03\x12!\n\x1d\x43ONFIG_CHANGE_STATUS_DEPLOYED\x10\x04\x12$\n CONFIG_CHANGE_STATUS_ROLLED_BACK\x10\x05\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.config_change_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_CONFIGCHANGESTATUS']._serialized_start=818
  _globals['_CONFIGCHANGESTATUS']._serialized_end=1053
  _globals['_CONFIGURATIONCHANGEREQUEST']._serialized_start=87
  _globals['_CONFIGURATIONCHANGEREQUEST']._serialized_end=523
  _globals['_CONFIGURATIONTHRESHOLDVERSION']._serialized_start=526
  _globals['_CONFIGURATIONTHRESHOLDVERSION']._serialized_end=815
# @@protoc_insertion_point(module_scope)
