# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/customer.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/customer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/customer.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n\x08\x43ustomer\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x03 \x01(\t\x12\x36\n\x06status\x18\x04 \x01(\x0e\x32&.ces.payment_resolution.CustomerStatus\x12\x30\n\x0c\x63reated_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rmodified_date\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xbd\x01\n\x08RiskFlag\x12\x0f\n\x07\x66lag_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x37\n\tflag_type\x18\x03 \x01(\x0e\x32$.ces.payment_resolution.RiskFlagType\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\x30\n\x0c\x66lagged_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05notes\x18\x06 \x01(\t*\xa4\x01\n\x0e\x43ustomerStatus\x12\x1f\n\x1b\x43USTOMER_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43USTOMER_STATUS_ACTIVE\x10\x01\x12\x1c\n\x18\x43USTOMER_STATUS_INACTIVE\x10\x02\x12\x1b\n\x17\x43USTOMER_STATUS_PENDING\x10\x03\x12\x1a\n\x16\x43USTOMER_STATUS_CLOSED\x10\x04*\xa0\x01\n\x0cRiskFlagType\x12\x1e\n\x1aRISK_FLAG_TYPE_UNSPECIFIED\x10\x00\x12 \n\x1cRISK_FLAG_TYPE_FRAUD_HISTORY\x10\x01\x12$\n RISK_FLAG_TYPE_SUSPENDED_ACCOUNT\x10\x02\x12(\n$RISK_FLAG_TYPE_CHRONIC_LATE_PAYMENTS\x10\x03\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.customer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_CUSTOMERSTATUS']._serialized_start=503
  _globals['_CUSTOMERSTATUS']._serialized_end=667
  _globals['_RISKFLAGTYPE']._serialized_start=670
  _globals['_RISKFLAGTYPE']._serialized_end=830
  _globals['_CUSTOMER']._serialized_start=82
  _globals['_CUSTOMER']._serialized_end=308
  _globals['_RISKFLAG']._serialized_start=311
  _globals['_RISKFLAG']._serialized_end=500
# @@protoc_insertion_point(module_scope)
