# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/document.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/document.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x02\n\x0c\x43\x61seDocument\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\x03\x12\x12\n\npayment_id\x18\x02 \x01(\t\x12\x13\n\x0buploaded_by\x18\x03 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\x12\x11\n\tfile_type\x18\x05 \x01(\t\x12\x17\n\x0f\x66ile_size_bytes\x18\x06 \x01(\x03\x12\x14\n\x0cstorage_path\x18\x07 \x01(\t\x12;\n\rdocument_type\x18\x08 \x01(\x0e\x32$.ces.payment_resolution.DocumentType\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12/\n\x0buploaded_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nis_deleted\x18\x0b \x01(\x08*\xfb\x01\n\x0c\x44ocumentType\x12\x1d\n\x19\x44OCUMENT_TYPE_UNSPECIFIED\x10\x00\x12%\n!DOCUMENT_TYPE_SUPPORTING_EVIDENCE\x10\x01\x12\'\n#DOCUMENT_TYPE_SENDER_CORRESPONDENCE\x10\x02\x12 \n\x1c\x44OCUMENT_TYPE_BANK_STATEMENT\x10\x03\x12\x1e\n\x1a\x44OCUMENT_TYPE_FRAUD_REPORT\x10\x04\x12!\n\x1d\x44OCUMENT_TYPE_POLICY_DOCUMENT\x10\x05\x12\x17\n\x13\x44OCUMENT_TYPE_OTHER\x10\x06\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_DOCUMENTTYPE']._serialized_start=397
  _globals['_DOCUMENTTYPE']._serialized_end=648
  _globals['_CASEDOCUMENT']._serialized_start=82
  _globals['_CASEDOCUMENT']._serialized_end=394
# @@protoc_insertion_point(module_scope)
