# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payment.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/payment.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x03\n\x07Payment\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x12\x13\n\x0bsender_name\x18\x03 \x01(\t\x12\x16\n\x0esender_account\x18\x04 \x01(\t\x12\x18\n\x10\x62\x65neficiary_name\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x30\n\x0cpayment_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11reference_field_1\x18\x08 \x01(\t\x12\x19\n\x11reference_field_2\x18\t \x01(\t\x12\x35\n\x06status\x18\n \x01(\x0e\x32%.ces.payment_resolution.PaymentStatus\x12\x1b\n\x13matched_customer_id\x18\x0b \x01(\t\x12\x19\n\x11matched_policy_id\x18\x0c \x01(\t\x12\x35\n\x11\x63reated_timestamp\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\x16investigation_due_date\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0csla_breached\x18\x0f \x01(\x08*\xad\x02\n\rPaymentStatus\x12\x1e\n\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n\x17PAYMENT_STATUS_RECEIVED\x10\x01\x12\x1d\n\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1a\n\x16PAYMENT_STATUS_APPLIED\x10\x03\x12\x17\n\x13PAYMENT_STATUS_HELD\x10\x04\x12\x1c\n\x18PAYMENT_STATUS_ESCALATED\x10\x05\x12$\n PAYMENT_STATUS_PROCESSING_FAILED\x10\x06\x12*\n&PAYMENT_STATUS_PENDING_SENDER_RESPONSE\x10\x07\x12\x1b\n\x17PAYMENT_STATUS_RETURNED\x10\x08\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_PAYMENTSTATUS']._serialized_start=576
  _globals['_PAYMENTSTATUS']._serialized_end=877
  _globals['_PAYMENT']._serialized_start=81
  _globals['_PAYMENT']._serialized_end=573
# @@protoc_insertion_point(module_scope)
