# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/policy.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/policy.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x03\n\x06Policy\x12\x15\n\rpolicy_number\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x13\n\x0bpolicy_type\x18\x03 \x01(\t\x12\x16\n\x0epremium_amount\x18\x04 \x01(\x03\x12\x43\n\x11premium_frequency\x18\x05 \x01(\x0e\x32(.ces.payment_resolution.PremiumFrequency\x12\x34\n\x06status\x18\x06 \x01(\x0e\x32$.ces.payment_resolution.PolicyStatus\x12\x1b\n\x13outstanding_balance\x18\x07 \x01(\x03\x12\x31\n\rnext_due_date\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63reated_date\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rmodified_date\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xe7\x01\n\x0ePaymentHistory\x12\x12\n\nhistory_id\x18\x01 \x01(\x03\x12\x11\n\tpolicy_id\x18\x02 \x01(\t\x12\x30\n\x0cpayment_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\x12\x16\n\x0epayment_method\x18\x05 \x01(\t\x12\x16\n\x0esender_account\x18\x06 \x01(\t\x12<\n\x06status\x18\x07 \x01(\x0e\x32,.ces.payment_resolution.PaymentHistoryStatus*\xb6\x01\n\x10PremiumFrequency\x12!\n\x1dPREMIUM_FREQUENCY_UNSPECIFIED\x10\x00\x12\x1d\n\x19PREMIUM_FREQUENCY_MONTHLY\x10\x01\x12\x1f\n\x1bPREMIUM_FREQUENCY_QUARTERLY\x10\x02\x12!\n\x1dPREMIUM_FREQUENCY_SEMI_ANNUAL\x10\x03\x12\x1c\n\x18PREMIUM_FREQUENCY_ANNUAL\x10\x04*}\n\x0cPolicyStatus\x12\x1d\n\x19POLICY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14POLICY_STATUS_ACTIVE\x10\x01\x12\x1a\n\x16POLICY_STATUS_INACTIVE\x10\x02\x12\x18\n\x14POLICY_STATUS_CLOSED\x10\x03*\xab\x01\n\x14PaymentHistoryStatus\x12&\n\"PAYMENT_HISTORY_STATUS_UNSPECIFIED\x10\x00\x12\"\n\x1ePAYMENT_HISTORY_STATUS_APPLIED\x10\x01\x12\"\n\x1ePAYMENT_HISTORY_STATUS_BOUNCED\x10\x02\x12#\n\x1fPAYMENT_HISTORY_STATUS_REVERSED\x10\x03\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_PREMIUMFREQUENCY']._serialized_start=718
  _globals['_PREMIUMFREQUENCY']._serialized_end=900
  _globals['_POLICYSTATUS']._serialized_start=902
  _globals['_POLICYSTATUS']._serialized_end=1027
  _globals['_PAYMENTHISTORYSTATUS']._serialized_start=1030
  _globals['_PAYMENTHISTORYSTATUS']._serialized_end=1201
  _globals['_POLICY']._serialized_start=80
  _globals['_POLICY']._serialized_end=481
  _globals['_PAYMENTHISTORY']._serialized_start=484
  _globals['_PAYMENTHISTORY']._serialized_end=715
# @@protoc_insertion_point(module_scope)
