# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/recommendation.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto import analytics_pb2 as proto_dot_analytics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/recommendation.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15proto/analytics.proto\"\xd9\x03\n\x15PaymentRecommendation\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12>\n\x0erecommendation\x18\x02 \x01(\x0e\x32&.ces.payment_resolution.Recommendation\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x01\x12=\n\x0escenario_route\x18\x04 \x01(\x0e\x32%.ces.payment_resolution.ScenarioRoute\x12\x15\n\rdecision_path\x18\x05 \x01(\t\x12\x1f\n\x17requires_human_approval\x18\x06 \x01(\x08\x12\x17\n\x0f\x61pproval_reason\x18\x07 \x01(\t\x12\x11\n\treasoning\x18\x08 \x03(\t\x12\x18\n\x10suggested_action\x18\t \x01(\t\x12\x1a\n\x12processing_time_ms\x18\n \x01(\x05\x12.\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12I\n\x14\x64\x65\x63ision_attribution\x18\x0c \x01(\x0e\x32+.ces.payment_resolution.DecisionAttribution*\x80\x01\n\x0eRecommendation\x12\x1e\n\x1aRECOMMENDATION_UNSPECIFIED\x10\x00\x12\x18\n\x14RECOMMENDATION_APPLY\x10\x01\x12\x17\n\x13RECOMMENDATION_HOLD\x10\x02\x12\x1b\n\x17RECOMMENDATION_ESCALATE\x10\x03*\x9d\x01\n\rScenarioRoute\x12\x1e\n\x1aSCENARIO_ROUTE_UNSPECIFIED\x10\x00\x12\x14\n\x10SCENARIO_ROUTE_1\x10\x01\x12\x14\n\x10SCENARIO_ROUTE_2\x10\x02\x12\x14\n\x10SCENARIO_ROUTE_3\x10\x03\x12\x14\n\x10SCENARIO_ROUTE_4\x10\x04\x12\x14\n\x10SCENARIO_ROUTE_5\x10\x05\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_RECOMMENDATION']._serialized_start=587
  _globals['_RECOMMENDATION']._serialized_end=715
  _globals['_SCENARIOROUTE']._serialized_start=718
  _globals['_SCENARIOROUTE']._serialized_end=875
  _globals['_PAYMENTRECOMMENDATION']._serialized_start=111
  _globals['_PAYMENTRECOMMENDATION']._serialized_end=584
# @@protoc_insertion_point(module_scope)
