# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/user.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x16\x63\x65s.payment_resolution\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12.\n\x04role\x18\x04 \x01(\x0e\x32 .ces.payment_resolution.UserRole\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x30\n\x0c\x63reated_date\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nlast_login\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x85\x01\n\x08UserRole\x12\x19\n\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x15\n\x11USER_ROLE_ANALYST\x10\x01\x12\x1a\n\x16USER_ROLE_INVESTIGATOR\x10\x02\x12\x16\n\x12USER_ROLE_DIRECTOR\x10\x03\x12\x13\n\x0fUSER_ROLE_ADMIN\x10\x04\x42\x34\n\x1a\x63om.ces.payment_resolutionZ\x16\x63\x65s/payment_resolutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ces.payment_resolutionZ\026ces/payment_resolution'
  _globals['_USERROLE']._serialized_start=298
  _globals['_USERROLE']._serialized_end=431
  _globals['_USER']._serialized_start=78
  _globals['_USER']._serialized_end=295
# @@protoc_insertion_point(module_scope)
